# This is a basic workflow to help you get started with Actions

name: Tweet Scheduler

# Controls when the workflow will run
on:

  # schedule:
  #   - cron: "*/25 * * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tweet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install dependency
        run: python -m pip install tweepy pendulum
      - name: Run script
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python main.py
      
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v10
        id: verify-changed-files
        with:
          files: |
            tweet.json
            **/*.jpeg
            **/*.jpg
            **/*.png
            **/*.gif
      
      - name: Commit and Push only when files change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --global user.name 'Automated Publisher'
          git config --global user.email 'actions@users.noreply.github.com'
          git add -A
          git commit -am "Future tweet"
          git push
